addons:
  - selenium

before_script:
  # Exit one errors.
  - set -e

  # Install webdriverCSS
  - cd ./visual-monitor
  - npm install
  - cd ..

  # Instead of composer install, we save time by using a gzipped file.
  - cd ./behat
  - tar zxf vendor_bin.tar.gz
  - cp behat.local.yml.shoov behat.local.yml
  - cd ..

script:
  - cd ./visual-monitor
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=ie11 mocha
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha
  - cd ..

  - cd ./behat
  - ./bin/behat
