before_script:
  # Exit one errors.
  - set -e

  # Install webdriverCSS
  - cd ./visual-monitor
  - npm install

script:
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=ie11 mocha
